# データの操作と可視化

## Numpyによる基本的なデータ操作

### 配列の定義と情報の取得

numpyの配列は`np.array`関数で定義できます。  
numpyのarrayは行列のような機能が実装されていて、自身の形状や大きさを属性として持ちます。

- `shape`: 行列の形を取得
- `size`: 要素数を取得

In [3]:
import numpy as np

In [11]:
# 1次元配列
arr_1d = np.array([1, 2, 3, 4])

# 2次元配列
arr_2d = np.array([[1, 2], [3, 4]])

print("1次元配列\n", arr_1d)
print("配列の形状とサイズ: ", arr_1d.shape, arr_1d.size)

print("2次元配列\n", arr_2d)
print("配列の形状とサイズ: ", arr_2d.shape, arr_2d.size)

1次元配列
 [1 2 3 4]
配列の形状とサイズ:  (4,) 4
2次元配列
 [[1 2]
 [3 4]]
配列の形状とサイズ:  (2, 2) 4


### 配列の操作

- 要素へのアクセス
- 形状の変更: `reshape`
- 結合: `concatenate`
  結合の向きは`axis`で指定します。


In [30]:
# 配列の定義
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print("元の配列\n", arr)

# 要素へのアクセス
print("要素へのアクセス")
print("[0, 1] -> ", arr[0, 1])
print("[:2, 2] -> ", arr[:2, 2])  # 1次元配列が返却される
print("[:2, [2]] -> ", arr[:2, [2]])  # 2*1の配列が返却される

# 形状の変更
print("形状の変更")
print("3 * 3 -> 1 * 9 に変換")
arr_19 = arr.reshape(1, 9)
print(arr_19, arr_19.shape)
print("3 * 3 -> 9 * 1 に変換")
arr_91 = arr.reshape(9, 1)
print(arr_91, arr_91.shape) 
# 1次元配列に変更
print("3 * 3 -> 9 に変換")
arr_9 = arr.reshape(9,)
print(arr_9, arr_9.shape)


元の配列
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
要素へのアクセス
[0, 1] ->  1
[:2, 2] ->  [2 5]
[:2, [2]] ->  [[2]
 [5]]
形状の変更
3 * 3 -> 1 * 9 に変換
[[0 1 2 3 4 5 6 7 8]] (1, 9)
3 * 3 -> 9 * 1 に変換
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]] (9, 1)
3 * 3 -> 9 に変換
[0 1 2 3 4 5 6 7 8] (9,)


In [40]:
# 配列の結合
print("結合する前のarrayを定義")
arr1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print("arr1: ", arr1.shape)
print(arr1)

arr2 = np.array([[-1, -2], [-5, -6]])

print("arr2: ", arr2.shape)
print(arr2)

arr３ = np.array([[-1, -2, -3, -4]])

print("arr３: ", arr３.shape)
print(arr３)

# 結合
print("縦方向に結合した配列")  
#.shapeの1つ目の要素の方向について結合するのでaxis=0を指定
arr_v = np.concatenate([arr1, arr3], axis=0)
print(arr_v)

print("横方向に結合した配列")
#.shapeの2つ目の要素の方向について結合するのでaxis=1を指定
arr_h = np.concatenate([arr1, arr2], axis=1)
print(arr_h)



結合する前のarrayを定義
arr1:  (2, 4)
[[1 2 3 4]
 [5 6 7 8]]
arr2:  (2, 2)
[[-1 -2]
 [-5 -6]]
arr３:  (1, 4)
[[-1 -2 -3 -4]]
縦方向に結合した配列
[[ 1  2  3  4]
 [ 5  6  7  8]
 [-1 -2 -3 -4]]
横方向に結合した配列
[[ 1  2  3  4 -1 -2]
 [ 5  6  7  8 -5 -6]]


### 配列の計算

numpyの`array`は基本的な四則演算はサポートされています。  
ただし、あくまで要素ごとの演算であり、内積や外積のような行列演算は別の関数が用意されています。

In [43]:
# 計算するための配列の定義
arr1 = np.array([1, 2, 3])
arr2 = np.array([2, 4, 6])

print("arr1: ", arr1)
print("arr2: ", arr2)

print("和: ", arr1 + arr2)
print("差: ", arr1 - arr2)
print("積: ", arr1 * arr2)
print("商: ", arr1 / arr2)

arr1:  [1 2 3]
arr2:  [2 4 6]
和:  [3 6 9]
差:  [-1 -2 -3]
積:  [ 2  8 18]
商:  [0.5 0.5 0.5]


形が合わないとエラーになりますが、結構柔軟に演算してくれます。  
逆に意図しない挙動の元になるので丁寧に確認した方が安全です。

In [54]:
# 形が違うとエラー
try:
    np.array([1, 2, 3]) + np.array([[2, 3], [5, 6]])
except Exception as e:
    print("Error: ", e)

# これは大丈夫
print("1次元配列 + 2次元配列 -> 1 * 3の2次元配列")
print(np.array([1, 2, 3]) + np.array([[1, 2, 3]]))

# これも大丈夫
print("1 * 3 + 3 * 1 -> 3 * 3")
print(np.array([1, 2, 3]).reshape(1, 3) + np.array([1, 2, 3]).reshape(3, 1))

# pythonの数値はすべての要素への演算
print("pythonの数値との演算")
print("np.array([1, 2, 3]) + 1:", np.array([1, 2, 3]) + 1)

Error:  operands could not be broadcast together with shapes (3,) (2,2) 
1次元配列 + 2次元配列 -> 1 * 3の2次元配列
[[2 4 6]]
1 * 3 + 3 * 1 -> 3 * 3
[[2 3 4]
 [3 4 5]
 [4 5 6]]
pythonの数値との演算
np.array([1, 2, 3]) + 1: [2 3 4]


### 統計的な情報の計算

行方向